ic_prob: 0.9597426875179622 #0.17357807091003608
jc_prob: 0.9597426875179622
optimization_rate: 25
# X, Y, Z, roll, pitch, yaw (in degrees)
odom_noise: [1.0e-2, 1.0e-2, 1.0e-2, 5.0, 5.0, 5.0]
# X, Y, Z, roll, pitch, yaw (in degrees)
meas_noise: [1.0e-1, 1.0e-1, 1.0e-1, 5.0, 5.0, 5.0]
prior_noise: [1.0e-3, 1.0e-3, 1.0e-3, 1.0, 1.0, 1.0]
should_log: true
number_of_messages_to_process: 5700 # Based on the number of messages in bag. 0 is infinite.

# 0 = JCBB, 1 = ML, 2 = Known data association
association_method: 2