ic_prob: 0.5
jc_prob: 0.9597426875179622
optimization_rate: 25
# roll, pitch, yaw, X, Y, Z (in degrees)
odom_noise: [1.0, 1.0, 1.0, 1.0e-3, 1.0e-3, 1.0e-3]
# roll, pitch, yaw, X, Y, Z (in degrees)
meas_noise: [5.0, 5.0, 5.0, 1.0e-2, 1.0e-2, 1.0e-2]
prior_noise: [1.0, 1.0, 1.0, 1.0e-3, 1.0e-3, 1.0e-3]
should_log: false
number_of_messages_to_process: 5700 # Based on the number of messages in bag. 0 is infinite.

# 0 = JCBB, 1 = ML, 2 = Known data association
association_method: 0

## JCBB params 5/12/21 20:26
# ic_prob: 0.5
# jc_prob: 0.9597426875179622

## ML params 5/12/21 20:41
# ic_prob: 0.9597426875179622 #0.5 #17357807091003608
# jc_prob: 0.9597426875179622